### 
GET http://127.0.0.1:8000/items/
Accept: application/json


### 
GET http://127.0.0.1:8000/items/?q=hola
Accept: application/json


### muy corto
GET http://127.0.0.1:8000/items/?q=ab
Accept: application/json


### muy largo
GET http://127.0.0.1:8000/items/?q=abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabc
Accept: application/json


